apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sadm
  labels:
    app: k8sadm
spec:
  selector:
    matchLabels:
      app: k8sadm
  replicas: 2
  template:
    metadata:
      name: k8sadm
      labels:
        app: k8sadm
    spec:
      containers:
        - name: k8sadm
          image: dongjoonju/k8sadm
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi